name: feedback_sentry
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app and upload it to Sentry.io
version: 3.2.0
homepage: https://uekoetter.dev
repository: https://github.com/ueman/feedback
issue_tracker: https://github.com/ueman/feedback/issues

funding:
  - https://github.com/sponsors/ueman

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  feedback:
    git:
      url: https://github.com/lezli01/feedback
      path: feedback
      ref: master
  sentry: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

